version: "3"

services:
  postgres:
    image: postgres:13
    container_name: java-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: java
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  user-notification-service:
    build:
      context: .
    image: usernotificationservice
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JOOQ_SQLDIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOWSQL: "true"
      SPRING_JPA_HIBERNATE_DDLDROP: create-drop
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
